// ─────────────────────────────────────────────
// Static Data for Germany Physics PhD Finder Agent
// For Nepali MSc Physics Students from Tribhuvan University
// ─────────────────────────────────────────────

export interface Institution {
  id: string
  name: string
  city: string
  country: string  // German state (Bundesland)
  type: 'University' | 'Research Institute' | 'Max Planck Institute'
  department: string
  researchGroup: string | null
  url: string
  fields: string
  phdType: string
  deadline: string
  admission: 'Rolling' | 'Semester-based'
  deadlines: {
    winter_semester: string
    summer_semester: string
    rolling: boolean
  }
  internationalTuitionEur: number
  funding: {
    doctoralScholarshipAvailable: boolean
    doctoralStipendEur: number
    daadEligible: boolean
    mpiPosition: boolean
    dfgFunded: boolean
    tu9University: boolean
    excellenceUniversity: boolean
  }
  ieltsMinimum: number
  contractType: string
  monthlyEur: number | null
  languageInstruction: string
  englishLabLife: boolean
  notableProfessors: string
  requiredDocuments: string
  notesForNepali: string
  watchlisted: boolean
  lastUpdated: string
  go8: boolean // TU9 flag for API compat
}

export interface ScholarshipInfo {
  id: string
  title: string
  category: string
  content: string
}

// ─────────────────────────────────────────────
// GERMAN UNIVERSITIES & RESEARCH INSTITUTES
// ─────────────────────────────────────────────
export const institutions: Institution[] = [
  // ========================
  // TU9 UNIVERSITIES (Top 9 Technical Universities)
  // ========================
  {
    id: 'tum',
    name: 'Technical University of Munich (TUM)',
    city: 'Munich',
    country: 'Bavaria',
    type: 'University',
    department: 'Department of Physics / TUM School of Natural Sciences',
    researchGroup: 'Quantum Optics, Condensed Matter, Particle Physics, Astrophysics',
    url: 'https://www.ph.tum.de/',
    fields: 'Quantum Optics|Condensed Matter|Particle Physics|Astrophysics|Nuclear Physics|Biophysics|Plasma Physics',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2138,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: true,
      excellenceUniversity: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'TV-L E13 (50-100%) or DFG/Excellence stipend',
    monthlyEur: 2138,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Harald Weinfurter (Quantum Optics), Prof. Stefan Schönert (Neutrino Physics), Prof. Frank Ortenburger (Theoretical Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'TUM is top-ranked globally. Many positions at MPI Quantum Optics are affiliated with TUM. No tuition fees! TV-L E13 contract provides excellent salary. DAAD scholarship also accepted.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'rwth-aachen',
    name: 'RWTH Aachen University',
    city: 'Aachen',
    country: 'North Rhine-Westphalia',
    type: 'University',
    department: 'Institute of Physics (IA)',
    researchGroup: 'Particle Physics, Condensed Matter, Quantum Information',
    url: 'https://www.physik.rwth-aachen.de/',
    fields: 'Particle Physics|Condensed Matter|Quantum Information|Materials Science|Nuclear Physics|Theoretical Physics',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2050,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: true,
      excellenceUniversity: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65%) or DFG project position',
    monthlyEur: 2050,
    languageInstruction: 'English (most groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Lutz Feld (Experimental Particle Physics), Prof. Markus Morgenstern (Condensed Matter)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'RWTH Aachen is Germany\'s largest technical university. Strong in particle physics (CERN collaboration). Close to Forschungszentrum Jülich. No tuition fees for PhD!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'tu-berlin',
    name: 'Technical University of Berlin (TU Berlin)',
    city: 'Berlin',
    country: 'Berlin',
    type: 'University',
    department: 'Institute of Optics and Atomic Physics',
    researchGroup: 'Quantum Optics, Photonics, Solid State Physics',
    url: 'https://www.tu.berlin/',
    fields: 'Quantum Optics|Photonics|Solid State Physics|Nanotechnology|Theoretical Physics',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 1950,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: true,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (50-75%) or university stipend',
    monthlyEur: 1950,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Wolfgang Ketterle alumni network, Prof. Sven Ramelow (Quantum Optics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Berlin is affordable for students! No tuition fees. Strong connections to MPI and HZB. Great city for international students with vibrant Nepali community.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'tu-darmstadt',
    name: 'TU Darmstadt',
    city: 'Darmstadt',
    country: 'Hesse',
    type: 'University',
    department: 'Department of Physics',
    researchGroup: 'Condensed Matter, Nuclear Physics, Photonics',
    url: 'https://www.physik.tu-darmstadt.de/',
    fields: 'Condensed Matter|Nuclear Physics|Photonics|Materials Science|Theoretical Physics|Quantum Computing',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 1950,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: true,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65%) or DFG project position',
    monthlyEur: 1950,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Norbert Pietralla (Nuclear Physics), Prof. Lambert Alff (Materials)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Close to GSI/FAIR accelerator facility - ideal for nuclear/particle physics. No tuition fees. Darmstadt is near Frankfurt with good Nepali community.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'tu-dresden',
    name: 'TU Dresden',
    city: 'Dresden',
    country: 'Saxony',
    type: 'University',
    department: 'Faculty of Physics',
    researchGroup: 'Condensed Matter, Quantum Materials, Theoretical Physics',
    url: 'https://tu-dresden.de/mn/physik/',
    fields: 'Condensed Matter|Quantum Materials|Theoretical Physics|Nanotechnology|Photonics|BioPhysics',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2050,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: true,
      excellenceUniversity: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65-75%) or Excellence cluster position',
    monthlyEur: 2050,
    languageInstruction: 'English (most groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Kornelius Nielsch (Quantum Materials), MPI-CPPS affiliated',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Excellence University! Home to cfaed (Center for Advancing Electronics Dresden). Strong MPI connections. Dresden is affordable. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'uni-stuttgart',
    name: 'University of Stuttgart',
    city: 'Stuttgart',
    country: 'Baden-Württemberg',
    type: 'University',
    department: 'Department of Physics',
    researchGroup: 'Quantum Optics, Condensed Matter, Photonics',
    url: 'https://www.physik.uni-stuttgart.de/',
    fields: 'Quantum Optics|Condensed Matter|Photonics|Materials Science|Theoretical Physics',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2050,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: true,
      excellenceUniversity: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65%) or SimTech stipend',
    monthlyEur: 2050,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Tilman Pfau (Quantum Optics), Prof. Martin Wegener (Nanophotonics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Stuttgart is Germany\'s high-tech hub. Home to SimTech excellence cluster. Great for quantum optics and nanophotonics. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'uni-hannover',
    name: 'Leibniz University Hannover',
    city: 'Hannover',
    country: 'Lower Saxony',
    type: 'University',
    department: 'Faculty of Mathematics and Physics',
    researchGroup: 'Quantum Optics, Gravitational Physics, Theoretical Physics',
    url: 'https://www.uni-hannover.de/',
    fields: 'Quantum Optics|Gravitational Physics|Theoretical Physics|Laser Physics|Quantum Information',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2050,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: true,
      excellenceUniversity: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65-75%) or Quantum Valley Lower Saxony stipend',
    monthlyEur: 2050,
    languageInstruction: 'English (most groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Roman Schnabel (Quantum Optics), Prof. Karsten Danzmann (Gravitational Physics, LIGO)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Home of GEO600 gravitational wave detector! Excellence University. Close to MPI for Gravitational Physics. Quantum Valley Lower Saxony cluster. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'tu-braunschweig',
    name: 'TU Braunschweig',
    city: 'Braunschweig',
    country: 'Lower Saxony',
    type: 'University',
    department: 'Institute of Physics',
    researchGroup: 'Condensed Matter, Metrology Physics, Particle Physics',
    url: 'https://www.tu-braunschweig.de/',
    fields: 'Condensed Matter|Metrology|Particle Physics|Materials Science|Theoretical Physics',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 1950,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: true,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65%) or PTB collaboration',
    monthlyEur: 1950,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. habil. Christoph Strunk (Condensed Matter), PTB affiliated researchers',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Home of PTB (German National Metrology Institute). Excellent for precision physics. Close to Hannover. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'tuhh',
    name: 'Hamburg University of Technology (TUHH)',
    city: 'Hamburg',
    country: 'Hamburg',
    type: 'University',
    department: 'Institute of Advanced Ceramics / Physics',
    researchGroup: 'Materials Physics, Photonics',
    url: 'https://www.tuhh.de/',
    fields: 'Materials Physics|Photonics|Theoretical Physics',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 1900,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: true,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65%) or project position',
    monthlyEur: 1900,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Gerold Schneider (Materials Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Hamburg has DESY and multiple MPIs nearby. TUHH is smaller but well-funded. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },

  // ========================
  // OTHER TOP GERMAN UNIVERSITIES
  // ========================
  {
    id: 'lmu-munich',
    name: 'Ludwig Maximilian University of Munich (LMU)',
    city: 'Munich',
    country: 'Bavaria',
    type: 'University',
    department: 'Faculty of Physics',
    researchGroup: 'Quantum Physics, Particle Physics, Astrophysics, Cosmology',
    url: 'https://www.physik.uni-muenchen.de/',
    fields: 'Quantum Physics|Particle Physics|Astrophysics|Cosmology|Condensed Matter|Theoretical Physics|Nuclear Physics',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2050,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'TV-L E13 (65-75%) or DFG/Excellence stipend',
    monthlyEur: 2050,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Theodor Hänsch (Nobel Laureate, Quantum Optics), Prof. Harald Lesch (Astrophysics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'LMU is one of Germany\'s most prestigious universities. Home to Nobel laureates. Connected to MPI for Quantum Optics and MPI for Astrophysics. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'uni-heidelberg',
    name: 'Heidelberg University',
    city: 'Heidelberg',
    country: 'Baden-Württemberg',
    type: 'University',
    department: 'Faculty of Physics and Astronomy',
    researchGroup: 'Particle Physics, Astrophysics, Quantum Dynamics, Condensed Matter',
    url: 'https://www.physik.uni-heidelberg.de/',
    fields: 'Particle Physics|Astrophysics|Quantum Dynamics|Condensed Matter|Nuclear Physics|Cosmology|Medical Physics',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2050,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'TV-L E13 (65-75%) or HGSFP stipend',
    monthlyEur: 2050,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Andreas Quadt (Particle Physics), Prof. Ralf Kähler (Astrophysics), MPI-K affiliated',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Germany\'s oldest university! Home to HGSFP (Heidelberg Graduate School for Physics). Connected to MPI for Nuclear Physics and MPI for Medical Research. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'uni-hamburg',
    name: 'University of Hamburg',
    city: 'Hamburg',
    country: 'Hamburg',
    type: 'University',
    department: 'Department of Physics',
    researchGroup: 'Particle Physics, Photon Science, Condensed Matter',
    url: 'https://www.physik.uni-hamburg.de/',
    fields: 'Particle Physics|Photon Science|Condensed Matter|Astrophysics|Quantum Physics|Laser Physics',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2050,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65-75%) or DESY/CUI stipend',
    monthlyEur: 2050,
    languageInstruction: 'English (most groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Caren Hagner (Neutrino Physics), Prof. Peter Hauschildt (Astrophysics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'DESY (German Electron Synchrotron) is right on campus! CUI (Center for Ultrafast Imaging) excellence cluster. Great for particle and photon science. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'uni-bonn',
    name: 'University of Bonn',
    city: 'Bonn',
    country: 'North Rhine-Westphalia',
    type: 'University',
    department: 'Institute of Physics',
    researchGroup: 'Particle Physics, Astrophysics, Theoretical Physics, Photonics',
    url: 'https://www.physics.uni-bonn.de/',
    fields: 'Particle Physics|Astrophysics|Theoretical Physics|Photonics|Condensed Matter|Nuclear Physics',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2050,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65%) or BCGS stipend',
    monthlyEur: 2050,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Norbert Wermes (Particle Physics), Prof. Stefan Tapprogge (Particle Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Bonn has BCGS (Bonn-Cologne Graduate School for Physics). Excellence University. Close to Forschungszentrum Jülich. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'uni-freiburg',
    name: 'University of Freiburg',
    city: 'Freiburg',
    country: 'Baden-Württemberg',
    type: 'University',
    department: 'Institute of Physics',
    researchGroup: 'Quantum Optics, Condensed Matter, Theoretical Physics',
    url: 'https://www.physik.uni-freiburg.de/',
    fields: 'Quantum Optics|Condensed Matter|Theoretical Physics|Nanotechnology|Photonics',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 1950,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65%) or DFG project position',
    monthlyEur: 1950,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Frank Stienkemeier (Ultrafast Spectroscopy), Prof. Michael Ritzert (Machine Learning + Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Freiburg is a beautiful, green city near the Black Forest. Very international. No tuition fees! Strong in quantum optics and ultrafast physics.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'uni-goettingen',
    name: 'University of Göttingen',
    city: 'Göttingen',
    country: 'Lower Saxony',
    type: 'University',
    department: 'Faculty of Physics',
    researchGroup: 'Condensed Matter, Astrophysics, Particle Physics, Biophysics',
    url: 'https://www.uni-goettingen.de/',
    fields: 'Condensed Matter|Astrophysics|Particle Physics|Biophysics|Theoretical Physics|Materials Science',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 1950,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65%) or MPI collaboration',
    monthlyEur: 1950,
    languageInstruction: 'English (most groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Cynthia Volkert (Materials Physics), MPI-DS affiliated researchers',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Göttingen is a legendary physics city (Gauss, Hilbert, Born, Heisenberg all worked here!). Connected to MPI for Dynamics and Self-Organization. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'uni-cologne',
    name: 'University of Cologne',
    city: 'Cologne',
    country: 'North Rhine-Westphalia',
    type: 'University',
    department: 'Institute of Physics',
    researchGroup: 'Quantum Materials, Astrophysics, Particle Physics',
    url: 'https://physics.uni-koeln.de/',
    fields: 'Quantum Materials|Astrophysics|Particle Physics|Theoretical Physics|Condensed Matter',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 1950,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65%) or BCGS stipend',
    monthlyEur: 1950,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Achim Rosch (Theoretical Physics), Prof. Markus Büscher (Particle Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Part of BCGS (Bonn-Cologne Graduate School). Strong in quantum materials and theoretical physics. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'uni-mainz',
    name: 'Johannes Gutenberg University Mainz',
    city: 'Mainz',
    country: 'Rhineland-Palatinate',
    type: 'University',
    department: 'Institute of Physics',
    researchGroup: 'Particle Physics, Quantum Optics, Condensed Matter, Nuclear Physics',
    url: 'https://www.physics.uni-mainz.de/',
    fields: 'Particle Physics|Quantum Optics|Condensed Matter|Nuclear Physics|Theoretical Physics|Materials Science',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 1950,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65%) or PRISMA+ cluster stipend',
    monthlyEur: 1950,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Ullrich (Atomic Physics), Prof. Hartmann (Theoretical Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Home to PRISMA+ Cluster of Excellence (particle & astroparticle physics). MAMI accelerator on campus. Close to Frankfurt. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'uni-jena',
    name: 'Friedrich Schiller University Jena',
    city: 'Jena',
    country: 'Thuringia',
    type: 'University',
    department: 'Institute of Optics and Quantum Electronics',
    researchGroup: 'Quantum Optics, Photonics, Ultrafast Physics',
    url: 'https://www.uni-jena.de/',
    fields: 'Quantum Optics|Photonics|Ultrafast Physics|Laser Physics|Quantum Information|Materials Science',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 1950,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65%) or Abbe School stipend',
    monthlyEur: 1950,
    languageInstruction: 'English (most groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Gerhard Paulus (Quantum Optics), Prof. Stefan Nolte (Photonics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Jena is "City of Light" - world center for optics and photonics! Home to Abbe School of Photonics. MPI for Quantum Optics affiliated. Close to Zeiss headquarters. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'uni-frankfurt',
    name: 'Goethe University Frankfurt',
    city: 'Frankfurt',
    country: 'Hesse',
    type: 'University',
    department: 'Institute of Physics',
    researchGroup: 'Particle Physics, Astrophysics, Condensed Matter, Theoretical Physics',
    url: 'https://www.physik.uni-frankfurt.de/',
    fields: 'Particle Physics|Astrophysics|Condensed Matter|Theoretical Physics|Nuclear Physics|Quantum Physics',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 1950,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65%) or DFG project position',
    monthlyEur: 1950,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Dirk Rischke (Theoretical Physics), Prof. Marcus Bleicher (Heavy Ion Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Frankfurt has a large Nepali community! FAIR/GSI is nearby. Good for particle and nuclear physics. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'uni-leipzig',
    name: 'University of Leipzig',
    city: 'Leipzig',
    country: 'Saxony',
    type: 'University',
    department: 'Faculty of Physics and Earth Sciences',
    researchGroup: 'Theoretical Physics, Condensed Matter, Biophysics',
    url: 'https://www.uni-leipzig.de/',
    fields: 'Theoretical Physics|Condensed Matter|Biophysics|Quantum Physics|Materials Science',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 1850,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65%) or DFG project position',
    monthlyEur: 1850,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Josef Käs (Biophysics), Prof. Bela Mulder (Theoretical Biophysics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Leipzig is very affordable! Growing international research community. Good for biophysics and theoretical physics. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'uni-konstanz',
    name: 'University of Konstanz',
    city: 'Konstanz',
    country: 'Baden-Württemberg',
    type: 'University',
    department: 'Department of Physics',
    researchGroup: 'Quantum Physics, Statistical Physics, Condensed Matter',
    url: 'https://www.uni-konstanz.de/',
    fields: 'Quantum Physics|Statistical Physics|Condensed Matter|Theoretical Physics|Nanotechnology',
    phdType: 'Dr. rer. nat. (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 1950,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65%) or CRC stipend',
    monthlyEur: 1950,
    languageInstruction: 'English (most groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Wolfgang Belzig (Quantum Physics), Prof. Clemens Bechinger (Statistical Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Excellence University! Small but excellent. On beautiful Lake Constance. Strong in quantum and statistical physics. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },

  // ========================
  // MAX PLANCK INSTITUTES (Physics-related)
  // ========================
  {
    id: 'mpq',
    name: 'Max Planck Institute for Quantum Optics (MPQ)',
    city: 'Garching near Munich',
    country: 'Bavaria',
    type: 'Max Planck Institute',
    department: 'Division of Quantum Dynamics / Laser Physics',
    researchGroup: 'Quantum Optics, Ultrafast Physics, Attosecond Physics, Quantum Information',
    url: 'https://www.mpq.mpg.de/',
    fields: 'Quantum Optics|Ultrafast Physics|Attosecond Physics|Quantum Information|Laser Physics|Plasma Physics',
    phdType: 'Dr. rer. nat. (3-5 years) via TUM or LMU',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Rolling', summer_semester: 'Rolling', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2138,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.5,
    contractType: 'TV-L E13 (75-100%) MPI contract',
    monthlyEur: 2138,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Ferenc Krausz (Nobel Laureate, Attosecond Physics), Prof. Immanuel Bloch (Quantum Many-Body Systems), Prof. Theodor Hänsch (Nobel Laureate)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, cover letter',
    notesForNepali: 'One of the world\'s top quantum optics institutes! Two Nobel laureates. Students registered at TUM or LMU. MPI contracts are very well-paid (TV-L E13 75-100%). No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'mpia',
    name: 'Max Planck Institute for Astronomy (MPIA)',
    city: 'Heidelberg',
    country: 'Baden-Württemberg',
    type: 'Max Planck Institute',
    department: 'Galaxies and Cosmology / Planet and Star Formation',
    researchGroup: 'Astrophysics, Exoplanets, Star Formation, Cosmology',
    url: 'https://www.mpia.de/',
    fields: 'Astrophysics|Exoplanets|Star Formation|Cosmology|Galaxy Evolution|Instrumentation',
    phdType: 'Dr. rer. nat. (3-5 years) via Heidelberg University',
    deadline: 'Nov 15 (annual IMPRS deadline)',
    admission: 'Semester-based',
    deadlines: { winter_semester: 'Nov 15', summer_semester: 'Rolling', rolling: false },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2138,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.5,
    contractType: 'TV-L E13 (75%) MPI contract + IMPRS-HD',
    monthlyEur: 2138,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Thomas Henning (Star Formation), Prof. Hans-Walter Rix (Galaxy Evolution)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, IMPRS application',
    notesForNepali: 'IMPRS (International Max Planck Research School) for Astronomy & Cosmic Physics. Students registered at Heidelberg. World-class telescopes access. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'mpifr',
    name: 'Max Planck Institute for Radio Astronomy (MPIfR)',
    city: 'Bonn',
    country: 'North Rhine-Westphalia',
    type: 'Max Planck Institute',
    department: 'Radio Astronomy / Millimetre and Submillimetre Astronomy',
    researchGroup: 'Radio Astronomy, Black Holes, Pulsars, Astrobiology',
    url: 'https://www.mpifr-bonn.mpg.de/',
    fields: 'Radio Astronomy|Black Holes|Pulsars|Astrobiology|Cosmology|VLBI',
    phdType: 'Dr. rer. nat. (3-5 years) via Bonn or Cologne',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Rolling', summer_semester: 'Rolling', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2138,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.5,
    contractType: 'TV-L E13 (75%) MPI contract',
    monthlyEur: 2138,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Michael Kramer (Pulsars), Prof. Karl Menten (Star Formation)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Operates the Effelsberg 100m radio telescope! Part of IMPRS for Astronomy & Astrophysics. Students at Bonn/Cologne. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'mpips',
    name: 'Max Planck Institute for the Physics of Complex Systems (MPI-PKS)',
    city: 'Dresden',
    country: 'Saxony',
    type: 'Max Planck Institute',
    department: 'Condensed Matter / Biological Physics / Nonlinear Dynamics',
    researchGroup: 'Quantum Many-Body, Biological Physics, Nonlinear Dynamics',
    url: 'https://www.pks.mpg.de/',
    fields: 'Quantum Many-Body|Biological Physics|Nonlinear Dynamics|Statistical Physics|Condensed Matter Theory|Quantum Information',
    phdType: 'Dr. rer. nat. (3-5 years) via TU Dresden',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Rolling', summer_semester: 'Rolling', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2138,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.5,
    contractType: 'TV-L E13 (75%) MPI contract',
    monthlyEur: 2138,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Jan-Michael Rost (Quantum Dynamics), Prof. Frank Jülicher (Biological Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Excellent for theoretical physics! Very international institute in Dresden. Students registered at TU Dresden. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'mpikf',
    name: 'Max Planck Institute for Nuclear Physics (MPIK)',
    city: 'Heidelberg',
    country: 'Baden-Württemberg',
    type: 'Max Planck Institute',
    department: 'Particle and Astroparticle Physics / Quantum Dynamics',
    researchGroup: 'Particle Physics, Nuclear Physics, Dark Matter, Neutrino Physics',
    url: 'https://www.mpi-hd.mpg.de/',
    fields: 'Particle Physics|Nuclear Physics|Dark Matter|Neutrino Physics|Astroparticle Physics|Quantum Dynamics',
    phdType: 'Dr. rer. nat. (3-5 years) via Heidelberg University',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Rolling', summer_semester: 'Rolling', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2138,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.5,
    contractType: 'TV-L E13 (75%) MPI contract',
    monthlyEur: 2138,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Manfred Lindner (Neutrino & Dark Matter), Prof. Christoph Wetterich (Theoretical Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Leading institute for dark matter and neutrino physics! Part of HGSFP. Connected to CERN and XENON collaboration. Students at Heidelberg. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'mpifs',
    name: 'Max Planck Institute for Solid State Research (MPI-FKF)',
    city: 'Stuttgart',
    country: 'Baden-Württemberg',
    type: 'Max Planck Institute',
    department: 'Condensed Matter / Quantum Materials / Nanoscience',
    researchGroup: 'Condensed Matter, Quantum Materials, Superconductivity, Topological Materials',
    url: 'https://www.fkf.mpg.de/',
    fields: 'Condensed Matter|Quantum Materials|Superconductivity|Topological Materials|Nanoscience|Spectroscopy',
    phdType: 'Dr. rer. nat. (3-5 years) via University of Stuttgart',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Rolling', summer_semester: 'Rolling', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2138,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.5,
    contractType: 'TV-L E13 (75%) MPI contract',
    monthlyEur: 2138,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Bernhard Keimer (Condensed Matter), Prof. Jürgen Smet (Quantum Hall)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'World-leading in condensed matter physics! High-Tc superconductivity research. Students at Stuttgart. Very well-funded. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'mpigrav',
    name: 'Max Planck Institute for Gravitational Physics (Albert Einstein Institute)',
    city: 'Potsdam / Hannover',
    country: 'Brandenburg / Lower Saxony',
    type: 'Max Planck Institute',
    department: 'Gravitational Physics / Quantum Gravity',
    researchGroup: 'Gravitational Waves, General Relativity, Quantum Gravity, LIGO/Virgo',
    url: 'https://www.aei.mpg.de/',
    fields: 'Gravitational Waves|General Relativity|Quantum Gravity|LIGO/Virgo|Black Holes|Cosmology',
    phdType: 'Dr. rer. nat. (3-5 years) via Hannover or Potsdam University',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Rolling', summer_semester: 'Rolling', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2138,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.5,
    contractType: 'TV-L E13 (75%) MPI contract',
    monthlyEur: 2138,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Bruce Allen (Gravitational Waves), Prof. Alessandra Buonanno (Gravitational Wave Theory)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'The Albert Einstein Institute! Key player in LIGO/Virgo gravitational wave detection. Two locations: Potsdam (theory) and Hannover (experiment). No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'mpids',
    name: 'Max Planck Institute for Dynamics and Self-Organization (MPI-DS)',
    city: 'Göttingen',
    country: 'Lower Saxony',
    type: 'Max Planck Institute',
    department: 'Nonlinear Dynamics / Fluid Dynamics / Network Dynamics',
    researchGroup: 'Fluid Dynamics, Nonlinear Dynamics, Complex Networks, Turbulence',
    url: 'https://www.ds.mpg.de/',
    fields: 'Fluid Dynamics|Nonlinear Dynamics|Complex Networks|Turbulence|Pattern Formation|Soft Matter',
    phdType: 'Dr. rer. nat. (3-5 years) via University of Göttingen',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Rolling', summer_semester: 'Rolling', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2138,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.5,
    contractType: 'TV-L E13 (75%) MPI contract',
    monthlyEur: 2138,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Eberhard Bodenschatz (Fluid Dynamics), Prof. Marc Timme (Network Dynamics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Excellent for nonlinear and complex systems! Very international. Students registered at Göttingen. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'mpihl',
    name: 'Max Planck Institute for Brain Research / Ernst Strüngmann Institute',
    city: 'Frankfurt',
    country: 'Hesse',
    type: 'Max Planck Institute',
    department: 'Neural Systems / Computational Neuroscience',
    researchGroup: 'Computational Neuroscience, Neural Physics, Brain Dynamics',
    url: 'https://www.mpi-brain.mpg.de/',
    fields: 'Computational Neuroscience|Neural Physics|Brain Dynamics|Biophysics|Statistical Physics',
    phdType: 'Dr. rer. nat. (3-5 years) via Goethe University Frankfurt',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Rolling', summer_semester: 'Rolling', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2138,
      daadEligible: true,
      mpiPosition: true,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.5,
    contractType: 'TV-L E13 (75%) MPI contract',
    monthlyEur: 2138,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Moritz Helmstaedter (Neural Circuits), Prof. Gilles Laurent (Neural Systems)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Great for physics students interested in neuroscience! Computational/theoretical neuroscience is very physics-adjacent. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },

  // ========================
  // OTHER RESEARCH INSTITUTES
  // ========================
  {
    id: 'desy',
    name: 'DESY (Deutsches Elektronen-Synchrotron)',
    city: 'Hamburg',
    country: 'Hamburg',
    type: 'Research Institute',
    department: 'Particle Physics / Photon Science',
    researchGroup: 'Particle Physics, Photon Science, Accelerator Physics',
    url: 'https://www.desy.de/',
    fields: 'Particle Physics|Photon Science|Accelerator Physics|X-ray Science|Free-Electron Lasers|Astroparticle Physics',
    phdType: 'Dr. rer. nat. (3-5 years) via University of Hamburg',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Rolling', summer_semester: 'Rolling', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2050,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.5,
    contractType: 'TV-L E13 (65-75%) DESY contract',
    monthlyEur: 2050,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Helmut Dosch (Photon Science), Prof. Beate Heinemann (Particle Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'DESY is Germany\'s national particle physics lab! Operates PETRA III and FLASH. Students at Hamburg University. Excellent for particle physics and photon science. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'gsi-fair',
    name: 'GSI/FAIR (Facility for Antiproton and Ion Research)',
    city: 'Darmstadt',
    country: 'Hesse',
    type: 'Research Institute',
    department: 'Nuclear Physics / Particle Physics / Atomic Physics',
    researchGroup: 'Nuclear Physics, Heavy Ion Physics, Antiproton Physics, Atomic Physics',
    url: 'https://www.gsi.de/',
    fields: 'Nuclear Physics|Heavy Ion Physics|Antiproton Physics|Atomic Physics|Plasma Physics|Radiation Physics',
    phdType: 'Dr. rer. nat. (3-5 years) via TU Darmstadt or Goethe University',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Rolling', summer_semester: 'Rolling', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2050,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65-75%) GSI/FAIR contract',
    monthlyEur: 2050,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Paolo Giubellino (FAIR Scientific Director), Prof. Henner Büsching (Nuclear Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'FAIR is a €3.2B new accelerator facility! One of the world\'s largest physics projects. Great for nuclear and particle physics. Students at Darmstadt or Frankfurt. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'fzj',
    name: 'Forschungszentrum Jülich (Jülich Research Centre)',
    city: 'Jülich',
    country: 'North Rhine-Westphalia',
    type: 'Research Institute',
    department: 'Institute of Complex Systems / Peter Grünberg Institute',
    researchGroup: 'Condensed Matter, Quantum Computing, Neuroscience, Nuclear Physics',
    url: 'https://www.fz-juelich.de/',
    fields: 'Condensed Matter|Quantum Computing|Neuroscience|Nuclear Physics|Materials Science|Supercomputing',
    phdType: 'Dr. rer. nat. (3-5 years) via RWTH Aachen or Bonn',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Rolling', summer_semester: 'Rolling', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2050,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65-75%) Jülich contract',
    monthlyEur: 2050,
    languageInstruction: 'English (most groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Stefan Blügel (Quantum Materials), Prof. Katrin Amunts (Neuroscience)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Has JUWELS supercomputer and PGI for quantum computing! Students at RWTH Aachen. Named after Nobel laureate Peter Grünberg. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'hzb',
    name: 'Helmholtz-Zentrum Berlin (HZB)',
    city: 'Berlin',
    country: 'Berlin',
    type: 'Research Institute',
    department: 'Materials / Energy / Information',
    researchGroup: 'Photon Science, Materials for Energy, Quantum Materials',
    url: 'https://www.helmholtz-berlin.de/',
    fields: 'Photon Science|Materials for Energy|Quantum Materials|Solar Energy|Neutron Scattering',
    phdType: 'Dr. rer. nat. (3-5 years) via TU Berlin or Humboldt University',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Rolling', summer_semester: 'Rolling', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 1950,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65%) HZB contract',
    monthlyEur: 1950,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Anke Kaysser-Pyzalla (Materials Science), Prof. Simone Raoux (Photon Science)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Operates BESSY II synchrotron! Great for materials and energy physics. Students at Berlin universities. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'kit',
    name: 'Karlsruhe Institute of Technology (KIT)',
    city: 'Karlsruhe',
    country: 'Baden-Württemberg',
    type: 'Research Institute',
    department: 'Institute of Physics',
    researchGroup: 'Particle Physics, Astroparticle Physics, Condensed Matter, Nuclear Physics',
    url: 'https://www.kit.edu/',
    fields: 'Particle Physics|Astroparticle Physics|Condensed Matter|Nuclear Physics|Quantum Materials|Accelerator Physics',
    phdType: 'Dr. rer. nat. (3-5 years) via KIT',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { winter_semester: 'Jul 15', summer_semester: 'Jan 15', rolling: true },
    internationalTuitionEur: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendEur: 2050,
      daadEligible: true,
      mpiPosition: false,
      dfgFunded: true,
      tu9University: false,
      excellenceUniversity: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'TV-L E13 (65-75%) KIT contract',
    monthlyEur: 2050,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Johannes Blümer (Astroparticle Physics), Prof. Wim de Boer (Particle Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'KIT is both a university AND a Helmholtz research centre! KATRIN neutrino experiment. Excellence University. No tuition fees!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
]

// ─────────────────────────────────────────────
// SCHOLARSHIP INFORMATION
// ─────────────────────────────────────────────
export const scholarships: ScholarshipInfo[] = [
  {
    id: 'daad-research-grants',
    title: 'DAAD Research Grants for Doctoral Candidates',
    category: 'DAAD Scholarships',
    content: 'The most important scholarship for Nepali students! DAAD (German Academic Exchange Service) offers fully funded PhD research grants. Covers monthly stipend of €1,300, health insurance, travel allowance from Nepal, and research material allowance. Duration: up to 3 years (can be extended). Apply through DAAD portal (deadline usually November). No tuition fees at German universities!',
  },
  {
    id: 'daad-euprogramme',
    title: 'DAAD Scholarships for Developing Countries',
    category: 'DAAD Scholarships',
    content: 'Special DAAD programme for students from developing countries including Nepal. Covers full PhD funding: €1,300/month stipend, health insurance, travel allowance, study and research allowance. Programme-specific deadlines, usually November for the following academic year. Requires IELTS 6.0-6.5 and strong academic record from TU.',
  },
  {
    id: 'daad-sandwich',
    title: 'DAAD Sandwich Model PhD',
    category: 'DAAD Scholarships',
    content: 'Unique programme where you do PhD research in Germany but degree is awarded by Tribhuvan University! Spend 1-2 years at a German university/research institute, then return to Nepal for thesis writing. Monthly stipend €1,300 + travel + insurance. Ideal for students who want to maintain their TU connection.',
  },
  {
    id: 'dfg-individual',
    title: 'DFG Individual Research Grants',
    category: 'DFG Funding',
    content: 'German Research Foundation (DFG) funds individual PhD positions through research projects. You apply to specific DFG-funded projects at universities. TV-L E13 salary (€1,950-2,138/month). Professors advertise these positions on their group websites and job portals. No separate scholarship application needed - apply directly to the position.',
  },
  {
    id: 'dfg-rtg',
    title: 'DFG Research Training Groups (RTG/CRC)',
    category: 'DFG Funding',
    content: 'Structured PhD programmes funded by DFG. Research Training Groups (Graduiertenkollegs) offer structured doctoral training with stipends or TV-L E13 positions. Collaborative Research Centers (CRC/SFB) also hire PhD students. These provide excellent supervision, structured curriculum, and networking. Apply directly to the RTG coordinator.',
  },
  {
    id: 'excellence-clusters',
    title: 'Excellence Cluster PhD Positions',
    category: 'Excellence Initiative',
    content: 'Germany\'s Excellence Strategy funds top research clusters that hire PhD students. Examples: PRISMA+ (Mainz), CUI (Hamburg), Quantum Universe (Hamburg), ct.qmat (Dresden/Würzburg), MCQST (Munich). TV-L E13 salary + additional benefits. Very competitive but excellent training.',
  },
  {
    id: 'imprs',
    title: 'International Max Planck Research Schools (IMPRS)',
    category: 'Max Planck',
    content: 'IMPRS are structured PhD programmes at Max Planck Institutes. Fully funded with TV-L E13 (75%) salary (~€2,138/month). International environment, English-language programme, excellent supervision. Apply through IMPRS portals (deadlines vary, often November for following year). Examples: IMPRS for Quantum Dynamics (MPQ), IMPRS for Astronomy (MPIA), IMPRS for Gravitational Wave Astronomy (AEI).',
  },
  {
    id: 'mpi-positions',
    title: 'Max Planck Institute PhD Positions',
    category: 'Max Planck',
    content: 'Direct PhD positions at MPIs outside of IMPRS. Apply directly to group leaders. TV-L E13 (75-100%) salary (€2,138-2,850/month). Very well-funded, excellent research infrastructure. Students registered at partner universities. Contact professors directly with your CV and research proposal.',
  },
  {
    id: 'helmholtz-phd',
    title: 'Helmholtz Association PhD Programme',
    category: 'Helmholtz Centres',
    content: 'Helmholtz research centres (DESY, GSI/FAIR, FZJ, HZB, KIT) offer PhD positions with TV-L E13 salary. Structured doctoral programmes with international exposure. Apply directly to advertised positions on Helmholtz job portal. DESY and GSI/FAIR are particularly relevant for physics.',
  },
  {
    id: 'erasmus-mundus',
    title: 'Erasmus Mundus Joint Doctorates',
    category: 'EU Programmes',
    content: 'EU-funded joint PhD programmes between universities in different countries. Full scholarship: €1,400-1,800/month + travel + insurance. Study in 2+ European countries. Physics programmes include: Joint Doctorate in Particle Physics, Quantum Science. Apply through programme websites (deadlines vary, usually January-March).',
  },
  {
    id: 'green-zi',
    title: 'Green ZI / Studienstiftung Scholarships',
    category: 'Foundation Scholarships',
    content: 'German foundations offer PhD scholarships: Studienstiftung des deutschen Volkes (€1,300-1,500/month), Friedrich-Ebert-Stiftung, Konrad-Adenauer-Stiftung, Heinrich-Böll-Stiftung. Require strong academics + social engagement. Some specifically for developing countries. Apply through foundation websites.',
  },
  {
    id: 'tu-scholarships',
    title: 'University-Specific Scholarships',
    category: 'University Scholarships',
    content: 'Many German universities offer their own PhD scholarships: TUM Graduate School fellowships, LMU promotionsstipendium, Heidelberg HGSFP, Hamburg CUI fellowships. Stipends typically €1,300-1,500/month. Check university graduate school websites for details and deadlines.',
  },
]

// ─────────────────────────────────────────────
// SEARCH FUNCTION
// ─────────────────────────────────────────────
export function searchScholarships(query: string): ScholarshipInfo[] {
  const q = query.toLowerCase()
  return scholarships.filter(
    (s) =>
      s.title.toLowerCase().includes(q) ||
      s.category.toLowerCase().includes(q) ||
      s.content.toLowerCase().includes(q)
  )
}
