// ─────────────────────────────────────────────
// Static Data for Australia Physics PhD Finder Agent
// For Nepali MSc Physics Students from Tribhuvan University
// ─────────────────────────────────────────────

export interface Institution {
  id: string
  name: string
  city: string
  state: 'NSW' | 'VIC' | 'QLD' | 'WA' | 'SA' | 'ACT' | 'TAS'
  type: 'University' | 'Research Institute'
  department: string
  researchGroup: string | null
  url: string
  fields: string
  phdType: string
  deadline: string
  admission: 'Rolling' | 'Semester-based'
  deadlines: {
    semester1_feb: string
    semester2_jul: string
    rolling: boolean
  }
  internationalTuitionAud: number
  funding: {
    rtpAvailable: boolean
    rtpStipendAud: number
    australiaAwardsEligible: boolean
    csiroTopup: boolean
    universityScholarships: boolean
  }
  ieltsMinimum: number
  contractType: string
  monthlyGbp: number | null // kept for API compat, stores AUD/month value
  languageInstruction: string
  englishLabLife: boolean
  notableProfessors: string
  requiredDocuments: string
  notesForNepali: string
  watchlisted: boolean
  lastUpdated: string
  country: string // alias for state for API compatibility
  go8: boolean // Group of Eight
}

export interface ScholarshipInfo {
  id: string
  title: string
  category: string
  content: string
}

// ─────────────────────────────────────────────
// AUSTRALIAN UNIVERSITIES (25+) & RESEARCH INSTITUTES
// ─────────────────────────────────────────────
export const institutions: Institution[] = [
  // ========================
  // GROUP OF EIGHT (Go8)
  // ========================
  {
    id: 'anu',
    name: 'Australian National University (ANU)',
    city: 'Canberra',
    state: 'ACT',
    type: 'University',
    department: 'Research School of Physics',
    researchGroup: 'ANU Centre for Gravitational Astrophysics',
    url: 'https://physics.anu.edu.au/',
    fields: 'Astrophysics|Quantum Physics|Nuclear Physics|Photonics|Condensed Matter|Theoretical Physics|Biomedical Physics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-02-24', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 49000,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: true, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + ANU University Research Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Susan Scott (Gravitational Waves), Prof David McClelland (Quantum Optics), Prof Mahananda Dasgupta (Nuclear Physics), Prof Vladislav Yakovlev (Photonics)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! ANU is the top-ranked university in Australia. Excellent for gravitational wave physics (LIGO collaboration). Rolling admissions make it flexible.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'ACT',
    go8: true,
  },
  {
    id: 'melbourne',
    name: 'University of Melbourne',
    city: 'Melbourne',
    state: 'VIC',
    type: 'University',
    department: 'School of Physics',
    researchGroup: 'ARC Centre of Excellence for Particle Physics',
    url: 'https://physics.unimelb.edu.au/',
    fields: 'Particle Physics|Astrophysics|Quantum Computing|Condensed Matter|Biophysics|Optical Physics|Theoretical Physics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-02-24', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 48500,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: true, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + Melbourne Research Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Geoffrey Taylor (ATLAS/CERN), Prof Rachel Webster (Astrophysics), Prof David Jamieson (Quantum), Prof Andy Martin (Nuclear Physics)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Top physics school in Australia. Strong CERN/ATLAS group. Melbourne is a vibrant city with large South Asian community.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'VIC',
    go8: true,
  },
  {
    id: 'sydney',
    name: 'University of Sydney',
    city: 'Sydney',
    state: 'NSW',
    type: 'University',
    department: 'School of Physics',
    researchGroup: 'Sydney Institute for Astronomy (SIfA)',
    url: 'https://www.sydney.edu.au/science/physics/',
    fields: 'Astrophysics|Quantum Physics|Photonics|Condensed Matter|Medical Physics|Complex Systems|Theoretical Physics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-03-02', semester2_jul: '2026-08-03', rolling: true },
    internationalTuitionAud: 49500,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: true, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + Sydney Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Elaine Sadler (ASTRO 3D), Prof Michael Biercuk (Quantum), Prof Ben Eggleton (Photonics), Prof David Reilly (Quantum Computing)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Outstanding astrophysics and quantum programs. Sydney has a large Nepali community in Harris Park/Parramatta area.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'NSW',
    go8: true,
  },
  {
    id: 'unsw',
    name: 'UNSW Sydney',
    city: 'Sydney',
    state: 'NSW',
    type: 'University',
    department: 'School of Physics',
    researchGroup: 'UNSW Quantum Computing',
    url: 'https://www.unsw.edu.au/science/physics',
    fields: 'Quantum Computing|Condensed Matter|Astrophysics|Nuclear Physics|Medical Physics|Photonics|Renewable Energy',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-02-17', semester2_jul: '2026-07-20', rolling: true },
    internationalTuitionAud: 48000,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: true, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + UNSW Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Michelle Simmons (Quantum Computing), Prof Sven Rogge (Quantum), Prof John Storey (Astrophysics), Prof Richard Newbury (Nuclear)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! World leader in quantum computing (silicon qubits). Michelle Simmons won the Finkel Prize. UNSW has strong industry partnerships.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'NSW',
    go8: true,
  },
  {
    id: 'uq',
    name: 'University of Queensland (UQ)',
    city: 'Brisbane',
    state: 'QLD',
    type: 'University',
    department: 'School of Mathematics and Physics',
    researchGroup: 'ARC Centre for Engineered Quantum Systems',
    url: 'https://smp.uq.edu.au/',
    fields: 'Quantum Physics|Condensed Matter|Astrophysics|Biophysics|Theoretical Physics|Nuclear Physics|Optical Physics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-02-24', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 46400,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: true, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + UQ Research Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Halina Rubinsztein-Dunlop (Quantum), Prof Andrew White (Quantum Computing), Prof Tamara Davis (Cosmology), Prof Warwick Bowen (Quantum Optomechanics)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Excellent quantum physics program (EQUS Centre). Brisbane is affordable with warm climate. Large Nepali student community.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'QLD',
    go8: true,
  },
  {
    id: 'monash',
    name: 'Monash University',
    city: 'Melbourne',
    state: 'VIC',
    type: 'University',
    department: 'School of Physics and Astronomy',
    researchGroup: 'Monash Centre for Astrophysics',
    url: 'https://www.monash.edu/science/schools/physics-astronomy',
    fields: 'Astrophysics|Condensed Matter|Quantum Physics|Medical Physics|Theoretical Physics|Particle Physics|Optical Physics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-03-02', semester2_jul: '2026-08-03', rolling: true },
    internationalTuitionAud: 47300,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: true, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + Monash Graduate Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof John Lattanzio (Astrophysics), Prof Michael Morgan (Medical Physics), Prof Meera Parish (Quantum), Prof Eric Thrane (Gravitational Waves)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Strong gravitational wave research (LIGO collaboration). Monash has generous international scholarships. Clayton campus has great facilities.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'VIC',
    go8: true,
  },
  {
    id: 'adelaide',
    name: 'University of Adelaide',
    city: 'Adelaide',
    state: 'SA',
    type: 'University',
    department: 'Department of Physics',
    researchGroup: 'ARC Centre for Dark Matter Particle Physics',
    url: 'https://www.adelaide.edu.au/science/physics/',
    fields: 'Dark Matter|Particle Physics|Astrophysics|Medical Physics|Nuclear Physics|Photonics|Theoretical Physics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-03-02', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 46500,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: false, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + Adelaide Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Martin White (Dark Matter), Prof Anthony Thomas (Nuclear), Prof Ivo Seitenzahl (Astrophysics), Prof David Ottaway (Gravitational Waves)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Leading dark matter research centre (CDMPP). Adelaide is one of the most affordable Australian cities. Stawell Underground Physics Lab nearby.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'SA',
    go8: true,
  },
  {
    id: 'uwa',
    name: 'University of Western Australia (UWA)',
    city: 'Perth',
    state: 'WA',
    type: 'University',
    department: 'Department of Physics',
    researchGroup: 'ARC Centre for Gravitational Wave Discovery (OzGrav)',
    url: 'https://www.uwa.edu.au/science/physics',
    fields: 'Gravitational Waves|Astrophysics|Quantum Physics|Medical Physics|Theoretical Physics|Condensed Matter',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-03-02', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 45000,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: true, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + UWA Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Linqing Wen (Gravitational Waves), Prof David Blair (LIGO), Prof Ju Li (Quantum), Prof Igor Bray (Theoretical Physics)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Key member of OzGrav (gravitational wave research). Perth has beautiful weather and lower cost of living. Close to Murchison Radio-astronomy Observatory.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'WA',
    go8: true,
  },
  // ========================
  // OTHER MAJOR UNIVERSITIES
  // ========================
  {
    id: 'curtin',
    name: 'Curtin University',
    city: 'Perth',
    state: 'WA',
    type: 'University',
    department: 'Department of Physics and Astronomy',
    researchGroup: 'Curtin Institute of Radio Astronomy',
    url: 'https://www.curtin.edu.au/study/offering/course-research-phd-physics/',
    fields: 'Radio Astronomy|Astrophysics|Quantum Computing|Medical Physics|Photonics|Theoretical Physics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-03-02', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 39500,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: true, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + Curtin Research Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Steven Tingay (Radio Astronomy), Prof Rainer Grun (Medical Physics), Prof Celine Boehm (Dark Matter), Prof Igor Bray (Theoretical)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Leading radio astronomy (SKA partner). Perth is affordable and beautiful. Curtin has strong industry links.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'WA',
    go8: false,
  },
  {
    id: 'macquarie',
    name: 'Macquarie University',
    city: 'Sydney',
    state: 'NSW',
    type: 'University',
    department: 'Department of Physics and Astronomy',
    researchGroup: 'ARC Centre for Ultrahigh bandwidth Devices for Optical Systems (CUDOS)',
    url: 'https://www.mq.edu.au/science/departments/physics-astronomy',
    fields: 'Photonics|Quantum Physics|Astrophysics|Condensed Matter|Medical Physics|Optical Physics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-02-24', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 40500,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: false, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + Macquarie Research Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof David Spence (Photonics), Prof Mark Wardle (Astrophysics), Prof Shellshear (Medical Physics), Prof Alex Zvyagin (Biophysics)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Excellent photonics program. Sydney location with more affordable cost than central Sydney. Good quantum and astronomy research.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'NSW',
    go8: false,
  },
  {
    id: 'swinburne',
    name: 'Swinburne University of Technology',
    city: 'Melbourne',
    state: 'VIC',
    type: 'University',
    department: 'Department of Physics and Astronomy',
    researchGroup: 'Centre for Astrophysics and Supercomputing',
    url: 'https://www.swinburne.edu.au/science/physics-astronomy/',
    fields: 'Astrophysics|Computational Physics|Quantum Physics|Photonics|Condensed Matter|Medical Physics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-03-02', semester2_jul: '2026-08-03', rolling: true },
    internationalTuitionAud: 37000,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: false, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + Swinburne Research Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Karl Glazebrook (Galaxies), Prof Jeremy Mould (Cosmology), Prof Alan Duffy (Astrophysics), Prof Virginia Kilborn (Radio Astronomy)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! World-class astrophysics and supercomputing. Home of the OzStar supercomputer. Lower tuition than Go8 but excellent research.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'VIC',
    go8: false,
  },
  {
    id: 'utas',
    name: 'University of Tasmania',
    city: 'Hobart',
    state: 'TAS',
    type: 'University',
    department: 'School of Natural Sciences (Physics)',
    researchGroup: 'ARC Centre of Excellence in Antarctic Science',
    url: 'https://www.utas.edu.au/natural-sciences/physics',
    fields: 'Atmospheric Physics|Astrophysics|Quantum Physics|Medical Physics|Condensed Matter|Geophysics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-02-24', semester2_jul: '2026-07-20', rolling: true },
    internationalTuitionAud: 36000,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: false, universityScholarships: true },
    ieltsMinimum: 6.0,
    contractType: 'RTP Stipend + UTAS Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Andrew Cole (Astrophysics), Prof Peter Reid (Medical Physics), Prof Kees Dullemond (Theoretical)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Most affordable Australian university. Unique access to Antarctic research. Lower IELTS requirement (6.0). Hobart is a beautiful, safe city.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'TAS',
    go8: false,
  },
  {
    id: 'latrobe',
    name: 'La Trobe University',
    city: 'Melbourne',
    state: 'VIC',
    type: 'University',
    department: 'Department of Physics and Astronomy',
    researchGroup: 'Centre for Materials and Surface Science',
    url: 'https://www.latrobe.edu.au/science/physics-astronomy',
    fields: 'Condensed Matter|Photonics|Medical Physics|Quantum Physics|Biophysics|Materials Science',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-03-02', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 37000,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: false, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + La Trobe Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Paul Pigram (Surface Science), Prof John Devlin (Condensed Matter), Prof David Hoxley (Photonics)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Strong in condensed matter and materials physics. Melbourne campus with good facilities. More accessible entry than Go8.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'VIC',
    go8: false,
  },
  {
    id: 'flinders',
    name: 'Flinders University',
    city: 'Adelaide',
    state: 'SA',
    type: 'University',
    department: 'College of Science and Engineering (Physics)',
    researchGroup: 'Institute for Nanoscale Science and Technology',
    url: 'https://www.flinders.edu.au/science-engineering/physics',
    fields: 'Nanophysics|Quantum Physics|Medical Physics|Photonics|Condensed Matter|Biophysics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-03-02', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 38000,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: false, universityScholarships: true },
    ieltsMinimum: 6.0,
    contractType: 'RTP Stipend + Flinders Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Nico Voelcker (Nanotech), Prof David Huang (Photonics), Prof Mark Bissett (Materials)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Lower IELTS requirement (6.0). Adelaide is very affordable. Strong nano and medical physics programs.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'SA',
    go8: false,
  },
  {
    id: 'newcastle',
    name: 'University of Newcastle',
    city: 'Newcastle',
    state: 'NSW',
    type: 'University',
    department: 'School of Mathematical and Physical Sciences',
    researchGroup: 'Centre for Organic Electronics',
    url: 'https://www.newcastle.edu.au/school/mathematical-physical-sciences',
    fields: 'Condensed Matter|Quantum Physics|Photonics|Medical Physics|Renewable Energy|Computational Physics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-02-24', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 38500,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: false, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + Newcastle Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Paul Dastoor (Organic Electronics), Prof Elena Ostrovskaya (Quantum), Prof Jim Franklin (Medical Physics)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Newcastle is affordable and 2hrs from Sydney. Strong in organic electronics and quantum research.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'NSW',
    go8: false,
  },
  {
    id: 'griffith',
    name: 'Griffith University',
    city: 'Brisbane',
    state: 'QLD',
    type: 'University',
    department: 'School of Environment and Science (Physics)',
    researchGroup: 'Centre for Quantum Dynamics',
    url: 'https://www.griffith.edu.au/science-aviation/physics',
    fields: 'Quantum Physics|Photonics|Condensed Matter|Environmental Physics|Theoretical Physics|Astrophysics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-03-02', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 37500,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: false, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + Griffith Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Howard Wiseman (Quantum), Prof Geoff Pryde (Quantum Optics), Prof David Pegg (Theoretical)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! World-leading quantum dynamics centre (Howard Wiseman, Geoff Pryde). Brisbane is warm and affordable.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'QLD',
    go8: false,
  },
  {
    id: 'jcu',
    name: 'James Cook University',
    city: 'Townsville',
    state: 'QLD',
    type: 'University',
    department: 'College of Science and Engineering (Physics)',
    researchGroup: 'Centre for Tropical Environmental and Sustainability Science',
    url: 'https://www.jcu.edu.au/college-of-science-and-engineering',
    fields: 'Environmental Physics|Marine Physics|Geophysics|Atmospheric Physics|Medical Physics|Renewable Energy',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-02-24', semester2_jul: '2026-07-20', rolling: true },
    internationalTuitionAud: 34000,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: false, universityScholarships: true },
    ieltsMinimum: 6.0,
    contractType: 'RTP Stipend + JCU Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Peter Ridd (Marine Physics), Prof Scott Bainbridge (Environmental Physics)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Lower IELTS (6.0). Very affordable. Unique tropical/marine physics research. Great for environmental physics focus.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'QLD',
    go8: false,
  },
  {
    id: 'uow',
    name: 'University of Wollongong',
    city: 'Wollongong',
    state: 'NSW',
    type: 'University',
    department: 'School of Physics',
    researchGroup: 'ARC Centre for Excellence in Future Low-Energy Electronics Technologies (FLEET)',
    url: 'https://www.uow.edu.au/science-medicine-health/physics/',
    fields: 'Condensed Matter|Quantum Physics|Medical Physics|Photonics|Materials Science|Superconductivity',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-02-24', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 37000,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: false, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + UOW Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Xiaolin Wang (Superconductivity), Prof Roger Lewis (Terahertz), Prof David Cortie (Condensed Matter)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Part of FLEET Centre. Wollongong is affordable, 1.5hrs from Sydney. Strong superconductivity and materials research.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'NSW',
    go8: false,
  },
  {
    id: 'wsu',
    name: 'Western Sydney University',
    city: 'Sydney',
    state: 'NSW',
    type: 'University',
    department: 'School of Science (Physics)',
    researchGroup: 'Biomedical Nanomaterials Group',
    url: 'https://www.westernsydney.edu.au/science/physics',
    fields: 'Nanophysics|Medical Physics|Photonics|Condensed Matter|Biophysics|Environmental Physics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-03-02', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 35500,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: false, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + WSU Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Anthony Dosseto (Environmental), Prof Gary Moloney (Nanophysics)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Sydney area but more affordable. Growing physics department. Good for nanophysics and medical physics.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'NSW',
    go8: false,
  },
  {
    id: 'rmit',
    name: 'RMIT University',
    city: 'Melbourne',
    state: 'VIC',
    type: 'University',
    department: 'School of Science (Physics)',
    researchGroup: 'Centre for Atom Trap Interferometry and Optics',
    url: 'https://www.rmit.edu.au/science/school-of-science/physics',
    fields: 'Quantum Physics|Photonics|Condensed Matter|Nanophysics|Computational Physics|Optical Physics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-03-02', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 39500,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: false, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + RMIT Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Peter Hannaford (Atom Optics), Prof Margarita Escudero (Condensed Matter), Prof Tim Davis (Photonics)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Strong in atom optics and quantum. Central Melbourne location. Industry-focused research.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'VIC',
    go8: false,
  },
  {
    id: 'qut',
    name: 'Queensland University of Technology (QUT)',
    city: 'Brisbane',
    state: 'QLD',
    type: 'University',
    department: 'School of Chemistry and Physics',
    researchGroup: 'QUT Centre for Materials Science',
    url: 'https://www.qut.edu.au/science-engineering/chemistry-physics',
    fields: 'Materials Physics|Condensed Matter|Nanophysics|Medical Physics|Photonics|Computational Physics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-02-24', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 37500,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: false, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + QUT Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Eric Waclawik (Nanophysics), Prof Dmitri Golberg (Materials), Prof Nunzio Motta (Nanotech)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Brisbane is affordable and warm. Strong materials and nano research. QUT has great industry connections.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'QLD',
    go8: false,
  },
  {
    id: 'deakin',
    name: 'Deakin University',
    city: 'Geelong',
    state: 'VIC',
    type: 'University',
    department: 'School of Life and Environmental Sciences (Physics)',
    researchGroup: 'Institute for Frontier Materials',
    url: 'https://www.deakin.edu.au/science-engineering-built-environment/physics',
    fields: 'Materials Physics|Photonics|Condensed Matter|Environmental Physics|Computational Physics|Nanophysics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-03-09', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 36000,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: false, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + Deakin Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Sally McArthur (Biomaterials), Prof Peter Hodgson (Materials)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Geelong is very affordable, 1hr from Melbourne. Strong materials science. Waurn Ponds campus has modern facilities.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'VIC',
    go8: false,
  },
  {
    id: 'uts',
    name: 'University of Technology Sydney (UTS)',
    city: 'Sydney',
    state: 'NSW',
    type: 'University',
    department: 'School of Mathematical and Physical Sciences',
    researchGroup: 'UTS Centre for Quantum Software and Information',
    url: 'https://www.uts.edu.au/mathematical-and-physical-sciences',
    fields: 'Quantum Computing|Quantum Information|Photonics|Condensed Matter|Computational Physics|Biophysics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-03-02', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 40000,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: true, csiroTopup: false, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'RTP Stipend + UTS Scholarship',
    monthlyGbp: 2683,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof Mingsheng Ying (Quantum Computing), Prof Runyao Duan (Quantum Information), Prof Seidel (Photonics)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS, Personal Statement',
    notesForNepali: 'Australia Awards eligible! Leading quantum computing research. Central Sydney location. Strong Chinese-Australian research collaborations.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'NSW',
    go8: false,
  },
  // ========================
  // CSIRO DIVISIONS (Research Institutes)
  // ========================
  {
    id: 'csiro-astronomy',
    name: 'CSIRO Astronomy and Space Science',
    city: 'Sydney',
    state: 'NSW',
    type: 'Research Institute',
    department: 'CSIRO Astronomy and Space Science',
    researchGroup: 'Australia Telescope National Facility (ATNF)',
    url: 'https://www.csiro.au/en/research/space-astronomy/astronomy',
    fields: 'Radio Astronomy|Astrophysics|Space Science|Instrumentation|Computational Astrophysics',
    phdType: 'PhD (via partner university)',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-02-24', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 0,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: false, csiroTopup: true, universityScholarships: false },
    ieltsMinimum: 6.5,
    contractType: 'CSIRO Postgraduate Scholarship + RTP',
    monthlyGbp: 3199,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Dr Lisa Harvey-Smith (Radio Astronomy), Dr George Hobbs (Pulsars), Dr Baerbel Koribalski (Galaxies)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS',
    notesForNepali: 'CSIRO top-up scholarship adds AUD$7,000-10,000/year on top of RTP! Operates the Australian Square Kilometre Array Pathfinder (ASKAP). Students enrol at partner university.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'NSW',
    go8: false,
  },
  {
    id: 'csiro-energy',
    name: 'CSIRO Energy',
    city: 'Newcastle',
    state: 'NSW',
    type: 'Research Institute',
    department: 'CSIRO Energy Centre',
    researchGroup: 'Renewable Energy Systems',
    url: 'https://www.csiro.au/en/research/technology-industry/energy',
    fields: 'Renewable Energy|Materials Science|Thermal Physics|Computational Physics|Photonics',
    phdType: 'PhD (via partner university)',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-02-24', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 0,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: false, csiroTopup: true, universityScholarships: false },
    ieltsMinimum: 6.5,
    contractType: 'CSIRO Postgraduate Scholarship + RTP',
    monthlyGbp: 3199,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Dr Wes Stein (Solar Thermal), Dr Drew Lilley (Energy Storage)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS',
    notesForNepali: 'CSIRO top-up available! Newcastle Energy Centre is world-class for renewable energy research. Students enrol at UoN or other partner universities.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'NSW',
    go8: false,
  },
  {
    id: 'csiro-manufacturing',
    name: 'CSIRO Manufacturing',
    city: 'Melbourne',
    state: 'VIC',
    type: 'Research Institute',
    department: 'CSIRO Manufacturing',
    researchGroup: 'Advanced Materials and Sensors',
    url: 'https://www.csiro.au/en/research/manufacturing',
    fields: 'Materials Science|Nanophysics|Photonics|Quantum Sensors|Surface Science|Biophysics',
    phdType: 'PhD (via partner university)',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-03-02', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 0,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: false, csiroTopup: true, universityScholarships: false },
    ieltsMinimum: 6.5,
    contractType: 'CSIRO Postgraduate Scholarship + RTP',
    monthlyGbp: 3199,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Dr Tim Davis (Photonics), Dr Daniel Gomez (Nanophotonics)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS',
    notesForNepali: 'CSIRO top-up available! Clayton campus in Melbourne. World-class nanofabrication facilities. Partner with Monash and Melbourne Uni.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'VIC',
    go8: false,
  },
  {
    id: 'csiro-minerals',
    name: 'CSIRO Mineral Resources',
    city: 'Perth',
    state: 'WA',
    type: 'Research Institute',
    department: 'CSIRO Mineral Resources',
    researchGroup: 'Geophysics and Remote Sensing',
    url: 'https://www.csiro.au/en/research/natural-resources/minerals',
    fields: 'Geophysics|Computational Physics|Materials Science|Environmental Physics|Remote Sensing',
    phdType: 'PhD (via partner university)',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-03-02', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 0,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: false, csiroTopup: true, universityScholarships: false },
    ieltsMinimum: 6.5,
    contractType: 'CSIRO Postgraduate Scholarship + RTP',
    monthlyGbp: 3199,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Dr James Cleverley (Computational Geoscience), Dr Caroline Mordensky (Mineral Physics)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS',
    notesForNepali: 'CSIRO top-up available! Perth location. Great for geophysics and computational physics. Partner with UWA and Curtin.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'WA',
    go8: false,
  },
  {
    id: 'csiro-oceans',
    name: 'CSIRO Oceans and Atmosphere',
    city: 'Hobart',
    state: 'TAS',
    type: 'Research Institute',
    department: 'CSIRO Oceans and Atmosphere',
    researchGroup: 'Marine and Atmospheric Research',
    url: 'https://www.csiro.au/en/research/environment/oceans',
    fields: 'Atmospheric Physics|Ocean Physics|Climate Physics|Computational Physics|Environmental Physics|Remote Sensing',
    phdType: 'PhD (via partner university)',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-02-24', semester2_jul: '2026-07-20', rolling: true },
    internationalTuitionAud: 0,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: false, csiroTopup: true, universityScholarships: false },
    ieltsMinimum: 6.5,
    contractType: 'CSIRO Postgraduate Scholarship + RTP',
    monthlyGbp: 3199,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Dr Steve Rintoul (Ocean Physics), Dr Simon Marsland (Climate)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS',
    notesForNepali: 'CSIRO top-up available! Hobart is beautiful and affordable. Access to Antarctic research vessels. Partner with UTas.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'TAS',
    go8: false,
  },
  {
    id: 'csiro-data61',
    name: "CSIRO Data61",
    city: 'Sydney',
    state: 'NSW',
    type: 'Research Institute',
    department: 'CSIRO Data61',
    researchGroup: 'Quantum Computing and Simulation',
    url: 'https://www.csiro.au/en/research/technology-industry/data',
    fields: 'Quantum Computing|Computational Physics|Machine Learning|Optimization|Statistical Physics|Complex Systems',
    phdType: 'PhD (via partner university)',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-02-24', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 0,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: false, csiroTopup: true, universityScholarships: false },
    ieltsMinimum: 6.5,
    contractType: 'CSIRO Postgraduate Scholarship + RTP',
    monthlyGbp: 3199,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Dr Muhammad Azam (Quantum Algorithms), Dr Neil Mallon (Optimization)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS',
    notesForNepali: 'CSIRO top-up available! Cutting-edge quantum computing research. Partner with UNSW and UTS. Marsfield campus in Sydney.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'NSW',
    go8: false,
  },
  // ========================
  // ANSTO
  // ========================
  {
    id: 'ansto',
    name: 'ANSTO (Australian Nuclear Science and Technology Organisation)',
    city: 'Sydney',
    state: 'NSW',
    type: 'Research Institute',
    department: 'ANSTO Bragg Institute',
    researchGroup: 'Neutron Scattering and Nuclear Physics',
    url: 'https://www.ansto.gov.au/',
    fields: 'Nuclear Physics|Neutron Scattering|Materials Science|Radiation Physics|Medical Physics|Condensed Matter|Environmental Physics',
    phdType: 'PhD (via partner university)',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { semester1_feb: '2026-02-24', semester2_jul: '2026-07-27', rolling: true },
    internationalTuitionAud: 0,
    funding: { rtpAvailable: true, rtpStipendAud: 32192, australiaAwardsEligible: false, csiroTopup: false, universityScholarships: true },
    ieltsMinimum: 6.5,
    contractType: 'ANSTO Postgraduate Scholarship + RTP',
    monthlyGbp: 3199,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Dr Vanessa Peterson (Neutron Scattering), Dr Richard Mole (Neutron Instruments), Prof Gordon Troup (Radiation Physics)',
    requiredDocuments: 'CV, Research Proposal, 2 References, Transcripts, IELTS',
    notesForNepali: 'ANSTO operates the OPAL research reactor and the Australian Centre for Neutron Scattering. Generous scholarship on top of RTP. Students enrol at partner universities (UNSW, ANU, etc.). Lucas Heights campus.',
    watchlisted: false,
    lastUpdated: '2026-01-15',
    country: 'NSW',
    go8: false,
  },
]

// ─────────────────────────────────────────────
// SCHOLARSHIPS (12+)
// ─────────────────────────────────────────────
export const scholarships: ScholarshipInfo[] = [
  // Australia Awards
  {
    id: 'australia-awards',
    title: 'Australia Awards Scholarship (MOST IMPORTANT for Nepali!)',
    category: 'Australia Awards',
    content: 'Fully funded scholarship for Nepali students! Covers full tuition, AUD $3,000/month stipend, return airfare from Nepal, Overseas Student Health Cover (OSHC), establishment allowance, and supplementary academic support. Apply through the Australian Awards Nepal office. The single most important scholarship route for Nepali Physics students aspiring to study in Australia.',
  },
  {
    id: 'australia-awards-short-course',
    title: 'Australia Awards Short Course Awards',
    category: 'Australia Awards',
    content: 'Short-term professional development courses (1-6 months) for Nepali professionals. Good stepping stone for building Australian academic connections before applying for full PhD. Covers travel, accommodation, and course fees.',
  },
  // RTP
  {
    id: 'rtp',
    title: 'Research Training Program (RTP) Stipend',
    category: 'Government Funding',
    content: 'Australian Government funded stipend for domestic and international HDR students. AUD $32,192/year (2025 rate), tax-free. Covers living costs for up to 3.5 years. Most universities offer RTP to international students. Apply directly through university graduate research admissions.',
  },
  {
    id: 'rtp-fee-offset',
    title: 'RTP Fee Offset Scholarship',
    category: 'Government Funding',
    content: 'Covers full international tuition fees for PhD students. Often combined with RTP Stipend to provide both tuition coverage and living allowance. Available at all Australian universities. Check individual university RTP allocation.',
  },
  // Endeavour
  {
    id: 'endeavour-leadership',
    title: 'Endeavour Leadership Program',
    category: 'Government Funding',
    content: 'Australian Government program for high-achieving international students. Provides up to AUD $140,000 for PhD research. Covers tuition, travel, and establishment. Competitive but excellent for Physics students with strong academic records.',
  },
  // University-specific
  {
    id: 'anu-research-scholarship',
    title: 'ANU University Research Scholarship',
    category: 'University Scholarships',
    content: 'Covers international student tuition fees at ANU. Combined with RTP Stipend, this provides full funding. ANU is the top-ranked university and offers generous support for international research students.',
  },
  {
    id: 'melbourne-research-scholarship',
    title: 'Melbourne Research Scholarship',
    category: 'University Scholarships',
    content: 'University of Melbourne provides fee remission and living allowance for international PhD students. Combined with RTP, total support exceeds AUD $80,000/year. One of the most generous university scholarships in Australia.',
  },
  {
    id: 'sydney-international-scholarship',
    title: 'University of Sydney International Scholarship',
    category: 'University Scholarships',
    content: 'Covers tuition fees and provides a living allowance for international HDR students at USyd. Additional funding available for research travel and conference attendance.',
  },
  {
    id: 'unsw-international-research',
    title: 'UNSW International Research Scholarship',
    category: 'University Scholarships',
    content: 'UNSW provides tuition fee scholarships and stipend top-ups for international research students, particularly in quantum computing and physics. Combined with RTP, very competitive package.',
  },
  {
    id: 'uq-international',
    title: 'UQ International Student Scholarship',
    category: 'University Scholarships',
    content: 'University of Queensland offers tuition fee waivers and top-up stipends for international research students. Combined with RTP and EQUS Centre funding, excellent support for quantum physics researchers.',
  },
  {
    id: 'monash-graduate-scholarship',
    title: 'Monash Graduate Scholarship (MGS)',
    category: 'University Scholarships',
    content: 'Provides a living allowance for international graduate research students at Monash. Combined with tuition scholarship and RTP, full funding is achievable. Monash has strong gravitational wave and astrophysics programs.',
  },
  // CSIRO
  {
    id: 'csiro-postgrad',
    title: 'CSIRO Postgraduate Scholarship',
    category: 'CSIRO Scholarships',
    content: 'CSIRO provides top-up scholarships of AUD $7,000-10,000/year on top of the university RTP stipend. Available across all CSIRO divisions including Astronomy, Energy, Manufacturing, Data61, and Oceans. Students must be enrolled at an Australian university and co-supervised by a CSIRO researcher.',
  },
  {
    id: 'csiro-data61-scholarship',
    title: 'CSIRO Data61 PhD Scholarship',
    category: 'CSIRO Scholarships',
    content: 'Specifically for quantum computing, machine learning, and computational physics research at Data61. Generous top-up on top of RTP stipend. Students work at Data61 facilities while enrolled at partner universities.',
  },
  {
    id: 'ansto-postgrad',
    title: 'ANSTO Postgraduate Scholarship',
    category: 'Research Institute Scholarships',
    content: 'ANSTO provides scholarships for PhD students using neutron scattering and nuclear physics facilities. Top-up of AUD $7,000-10,000/year on top of RTP. Access to OPAL reactor and Australian Centre for Neutron Scattering. Students enrol at partner universities.',
  },
]

// ─────────────────────────────────────────────
// SEARCH FUNCTION
// ─────────────────────────────────────────────
export function searchScholarships(query: string): ScholarshipInfo[] {
  const q = query.toLowerCase()
  return scholarships.filter(
    (s) =>
      s.title.toLowerCase().includes(q) ||
      s.category.toLowerCase().includes(q) ||
      s.content.toLowerCase().includes(q)
  )
}
