// ─────────────────────────────────────────────
// Static Data for Japan Physics PhD Finder Agent
// For Nepali MSc Physics Students from Tribhuvan University
// ─────────────────────────────────────────────

export interface Institution {
  id: string
  name: string
  city: string
  prefecture: string
  type: 'National University' | 'Private University' | 'Research Institute'
  department: string
  researchGroup: string | null
  url: string
  fields: string
  phdType: string
  deadline: string
  aprilDeadline: string
  octoberDeadline: string
  aprilIntake: boolean
  octoberIntake: boolean
  englishProgram: boolean
  tuitionJpy: number
  mextDesignated: boolean
  jlptRequired: boolean
  englishTest: string
  monthlyStipendJpy: number | null
  fundingType: string
  requiredDocuments: string
  notableProfessors: string
  rikenAffiliated: boolean
  watchlisted: boolean
  lastUpdated: string
  notesForNepali: string
}

export interface ScholarshipInfo {
  id: string
  title: string
  category: string
  content: string
}

// ─────────────────────────────────────────────
// UNIVERSITIES (35+)
// ─────────────────────────────────────────────
export const institutions: Institution[] = [
  // ========================
  // NATIONAL UNIVERSITIES (Top tier)
  // ========================
  {
    id: 'utokyo',
    name: 'University of Tokyo',
    city: 'Tokyo',
    prefecture: 'Tokyo',
    type: 'National University',
    department: 'Department of Physics, Graduate School of Science',
    researchGroup: 'Multiple research groups',
    url: 'https://www.phys.s.u-tokyo.ac.jp/en/',
    fields: 'Astrophysics|Condensed Matter|Particle Physics|Biophysics|Nuclear Physics|Quantum Mechanics',
    phdType: 'Research Student + Doctoral Program',
    deadline: 'Varies by department',
    aprilDeadline: 'December (MEXT)',
    octoberDeadline: 'April (MEXT)',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | JSPS | University Fellowship',
    requiredDocuments: 'Research proposal|Transcripts|TOEFL/IELTS|Reference letters|Application form',
    notableProfessors: 'Takaaki Kajita (Nobel 2015, Neutrino)|Masato Hagiwara (Quantum Computing)',
    rikenAffiliated: true,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Top choice for MEXT. Strong in all physics fields. English programs available. Large Nepali community in Tokyo.',
  },
  {
    id: 'kyoto-u',
    name: 'Kyoto University',
    city: 'Kyoto',
    prefecture: 'Kyoto',
    type: 'National University',
    department: 'Department of Physics, Graduate School of Science',
    researchGroup: 'Yukawa Institute for Theoretical Physics',
    url: 'https://www.phys.kyoto-u.ac.jp/en/',
    fields: 'Particle Physics|Condensed Matter|Astrophysics|Nuclear Physics|Biophysics|Quantum Mechanics',
    phdType: 'Research Student + Doctoral Program',
    deadline: 'Varies by department',
    aprilDeadline: 'December (MEXT)',
    octoberDeadline: 'April (MEXT)',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | JSPS | University Fellowship',
    requiredDocuments: 'Research proposal|Transcripts|TOEFL/IELTS|Reference letters|Application form',
    notableProfessors: 'Yukawa Institute faculty (Theoretical Physics)|Kavli IPMU affiliated researchers',
    rikenAffiliated: true,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Home of Yukawa Institute for Theoretical Physics. Very strong in particle and theoretical physics. Historic city with lower living costs.',
  },
  {
    id: 'osaka-u',
    name: 'Osaka University',
    city: 'Osaka',
    prefecture: 'Osaka',
    type: 'National University',
    department: 'Department of Physics, Graduate School of Science',
    researchGroup: null,
    url: 'https://www.phys.sci.osaka-u.ac.jp/en/',
    fields: 'Condensed Matter|Particle Physics|Nuclear Physics|Astrophysics|Quantum Mechanics|Laser Physics',
    phdType: 'Doctoral Program',
    deadline: 'January (April) / July (October)',
    aprilDeadline: 'January',
    octoberDeadline: 'July',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | JSPS | University',
    requiredDocuments: 'Research proposal|Transcripts|English test|References|Application form',
    notableProfessors: 'RCNP faculty (Nuclear Physics)|Takashi Nakano (Hadron Physics)',
    rikenAffiliated: true,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Strong in nuclear and hadron physics via RCNP. Good English support. Osaka is affordable.',
  },
  {
    id: 'tohoku-u',
    name: 'Tohoku University',
    city: 'Sendai',
    prefecture: 'Miyagi',
    type: 'National University',
    department: 'Department of Physics, Graduate School of Science',
    researchGroup: null,
    url: 'https://www.phys.tohoku.ac.jp/en/',
    fields: 'Condensed Matter|Astrophysics|Particle Physics|Nuclear Physics|Magnetism|Materials Science',
    phdType: 'Doctoral Program',
    deadline: 'December (April) / June (October)',
    aprilDeadline: 'December',
    octoberDeadline: 'June',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | JSPS | University',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'IMR faculty (Materials)|WPI-AIMR researchers',
    rikenAffiliated: true,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Excellent for condensed matter and magnetism. Sendai is beautiful and affordable. Strong international student support.',
  },
  {
    id: 'nagoya-u',
    name: 'Nagoya University',
    city: 'Nagoya',
    prefecture: 'Aichi',
    type: 'National University',
    department: 'Department of Physics, Graduate School of Science',
    researchGroup: 'Kobayashi-Maskawa Institute',
    url: 'https://www.phys.nagoya-u.ac.jp/e/',
    fields: 'Particle Physics|Astrophysics|Condensed Matter|Quantum Mechanics|Nuclear Physics',
    phdType: 'Doctoral Program',
    deadline: 'January (April) / July (October)',
    aprilDeadline: 'January',
    octoberDeadline: 'July',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | JSPS | University',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'Kobayashi-Maskawa Institute (Nobel 2008)|ICRR affiliated',
    rikenAffiliated: true,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Home of Kobayashi-Maskawa Institute. Very strong in particle physics. Central Japan location.',
  },
  {
    id: 'tokyo-tech',
    name: 'Institute of Science Tokyo (Former Tokyo Tech)',
    city: 'Tokyo',
    prefecture: 'Tokyo',
    type: 'National University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.titech.ac.jp/english/',
    fields: 'Condensed Matter|Quantum Mechanics|Optics|Biophysics|Materials Science|Computational Physics',
    phdType: 'Doctoral Program',
    deadline: 'December (April) / May (October)',
    aprilDeadline: 'December',
    octoberDeadline: 'May',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | JSPS | University',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'Multiple materials science groups',
    rikenAffiliated: true,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Merged with Tokyo Medical and Dental University. Excellent for applied physics and materials.',
  },
  {
    id: 'hokkaido-u',
    name: 'Hokkaido University',
    city: 'Sapporo',
    prefecture: 'Hokkaido',
    type: 'National University',
    department: 'Department of Physics, Graduate School of Science',
    researchGroup: null,
    url: 'https://www.sci.hokudai.ac.jp/phys/e/',
    fields: 'Condensed Matter|Astrophysics|Nuclear Physics|Biophysics|Geophysics|Low Temperature Physics',
    phdType: 'Doctoral Program',
    deadline: 'December (April) / June (October)',
    aprilDeadline: 'December',
    octoberDeadline: 'June',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'Low temperature physics group|Creative Research Institution faculty',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Excellent for low temperature and condensed matter physics. Sapporo has cold winters but is very beautiful. Lower cost of living.',
  },
  {
    id: 'kyushu-u',
    name: 'Kyushu University',
    city: 'Fukuoka',
    prefecture: 'Fukuoka',
    type: 'National University',
    department: 'Department of Physics, Graduate School of Science',
    researchGroup: null,
    url: 'https://www.phys.kyushu-u.ac.jp/en/',
    fields: 'Condensed Matter|Astrophysics|Particle Physics|Quantum Mechanics|AMO Physics',
    phdType: 'Doctoral Program',
    deadline: 'January (April) / July (October)',
    aprilDeadline: 'January',
    octoberDeadline: 'July',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'AMO physics group|Quantum materials researchers',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Good AMO and condensed matter programs. Fukuoka is warm and affordable. Growing international community.',
  },
  {
    id: 'hiroshima-u',
    name: 'Hiroshima University',
    city: 'Hiroshima',
    prefecture: 'Hiroshima',
    type: 'National University',
    department: 'Department of Physics, Graduate School of Science',
    researchGroup: null,
    url: 'https://www.hiroshima-u.ac.jp/en',
    fields: 'Condensed Matter|Particle Physics|Nuclear Physics|Astrophysics|Materials Science',
    phdType: 'Doctoral Program',
    deadline: 'December (April) / June (October)',
    aprilDeadline: 'December',
    octoberDeadline: 'June',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'RCAPP faculty (Astroparticle Physics)',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Strong in nuclear and particle physics. Peace Memorial City. Good support for international students.',
  },
  {
    id: 'tsukuba-u',
    name: 'University of Tsukuba',
    city: 'Tsukuba',
    prefecture: 'Ibaraki',
    type: 'National University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.tsukuba.ac.jp/en/',
    fields: 'Condensed Matter|Particle Physics|Astrophysics|Materials Science|Nuclear Physics',
    phdType: 'Doctoral Program',
    deadline: 'December (April) / June (October)',
    aprilDeadline: 'December',
    octoberDeadline: 'June',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University | KEK affiliated',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'KEK affiliated researchers|Tsukuba materials science groups',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Located in Tsukuba Science City. Close to KEK. Very strong research environment. Many international researchers.',
  },

  // ========================
  // MORE NATIONAL UNIVERSITIES
  // ========================
  {
    id: ' Kobe-u',
    name: 'Kobe University',
    city: 'Kobe',
    prefecture: 'Hyogo',
    type: 'National University',
    department: 'Department of Physics, Graduate School of Science',
    researchGroup: null,
    url: 'https://www.kobe-u.ac.jp/en/',
    fields: 'Condensed Matter|Particle Physics|Astrophysics|Biophysics',
    phdType: 'Doctoral Program',
    deadline: 'January (April) / July (October)',
    aprilDeadline: 'January',
    octoberDeadline: 'July',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'RCNP affiliated faculty',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Good physics program. Kobe is a beautiful port city.',
  },
  {
    id: 'waseda-u',
    name: 'Waseda University',
    city: 'Tokyo',
    prefecture: 'Tokyo',
    type: 'Private University',
    department: 'Department of Physics, School of Advanced Science and Engineering',
    researchGroup: null,
    url: 'https://www.waseda.jp/fsci/en/',
    fields: 'Condensed Matter|Quantum Mechanics|Optics|Biophysics|Materials Science',
    phdType: 'Doctoral Program',
    deadline: 'Varies',
    aprilDeadline: 'November',
    octoberDeadline: 'May',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 800000,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University Scholarship',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'Quantum computing groups',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Private university but MEXT covers tuition. Strong international programs.',
  },
  {
    id: 'keio-u',
    name: 'Keio University',
    city: 'Yokohama',
    prefecture: 'Kanagawa',
    type: 'Private University',
    department: 'Department of Physics, Faculty of Science and Technology',
    researchGroup: null,
    url: 'https://www.keio.ac.jp/en/',
    fields: 'Condensed Matter|Quantum Mechanics|Optics|AMO Physics|Materials Science',
    phdType: 'Doctoral Program',
    deadline: 'Varies',
    aprilDeadline: 'November',
    octoberDeadline: 'May',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 800000,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University Scholarship',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'Quantum information groups',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Private but MEXT eligible. Strong in quantum information. Near Tokyo.',
  },

  // ========================
  // RESEARCH INSTITUTES
  // ========================
  {
    id: 'riken',
    name: 'RIKEN',
    city: 'Wako',
    prefecture: 'Saitama',
    type: 'Research Institute',
    department: 'Multiple research centers',
    researchGroup: 'Nishina Center|Center for Quantum Computing|Center for Emergent Matter Science',
    url: 'https://www.riken.jp/en/',
    fields: 'Particle Physics|Nuclear Physics|Condensed Matter|Quantum Computing|Materials Science|Biophysics',
    phdType: 'Junior Research Associate (JRA) | Joint PhD with universities',
    deadline: 'Rolling (JRA: April & October)',
    aprilDeadline: 'January (JRA)',
    octoberDeadline: 'July (JRA)',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 0,
    mextDesignated: false,
    jlptRequired: false,
    englishTest: 'English sufficient',
    monthlyStipendJpy: 200000,
    fundingType: 'RIKEN JRA Stipend',
    requiredDocuments: 'Research proposal|CV|Transcripts|Reference letters|Application form',
    notableProfessors: 'Nishina Center faculty|CQC researchers|CEMS researchers',
    rikenAffiliated: true,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'JRA program offers ¥200,000+/month! Joint PhD with UTokyo/Kyoto/etc. World-class research. Highly recommended.',
  },
  {
    id: 'kek',
    name: 'KEK (High Energy Accelerator Research Organization)',
    city: 'Tsukuba',
    prefecture: 'Ibaraki',
    type: 'Research Institute',
    department: 'Institute of Particle and Nuclear Studies|Institute of Materials Structure Science',
    researchGroup: null,
    url: 'https://www.kek.jp/en/',
    fields: 'Particle Physics|Nuclear Physics|Materials Science|Accelerator Physics',
    phdType: 'Joint PhD with universities (SOKENDAI)',
    deadline: 'Varies (SOKENDAI schedule)',
    aprilDeadline: 'December',
    octoberDeadline: 'June',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 0,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT via SOKENDAI | KEK fellowship',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'Belle II collaboration|J-PARC researchers',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Home of Belle II and J-PARC. SOKENDAI is the graduate university. MEXT covers everything. Excellent for particle physics.',
  },
  {
    id: 'nims',
    name: 'NIMS (National Institute for Materials Science)',
    city: 'Tsukuba',
    prefecture: 'Ibaraki',
    type: 'Research Institute',
    department: 'Multiple research centers',
    researchGroup: null,
    url: 'https://www.nims.go.jp/eng/',
    fields: 'Materials Science|Condensed Matter|Nanotechnology|Superconductivity|Magnetism',
    phdType: 'Joint PhD with universities',
    deadline: 'Rolling',
    aprilDeadline: 'Varies',
    octoberDeadline: 'Varies',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 0,
    mextDesignated: false,
    jlptRequired: false,
    englishTest: 'English sufficient',
    monthlyStipendJpy: 180000,
    fundingType: 'NIMS fellowship',
    requiredDocuments: 'Research proposal|CV|Transcripts|References',
    notableProfessors: 'International Center for Materials Nanoarchitectonics faculty',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: '¥180,000/month fellowship. World-leading in materials science. Joint PhD with University of Tsukuba and others.',
  },
  {
    id: 'j-parc',
    name: 'J-PARC Center',
    city: 'Tokai',
    prefecture: 'Ibaraki',
    type: 'Research Institute',
    department: 'Particle and Nuclear Physics',
    researchGroup: null,
    url: 'https://j-parc.jp/en/',
    fields: 'Particle Physics|Nuclear Physics|Neutrino Physics|Accelerator Physics|Materials Science',
    phdType: 'Joint PhD via KEK',
    deadline: 'Via KEK/SOKENDAI',
    aprilDeadline: 'December',
    octoberDeadline: 'June',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 0,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT via KEK',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'T2K collaboration researchers',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'World-class accelerator facility. Apply through KEK/SOKENDAI. T2K neutrino experiment.',
  },

  // ========================
  // MORE NATIONAL UNIVERSITIES
  // ========================
  {
    id: 'okayama-u',
    name: 'Okayama University',
    city: 'Okayama',
    prefecture: 'Okayama',
    type: 'National University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.okayama-u.ac.jp/en/',
    fields: 'Condensed Matter|Particle Physics|Astrophysics|Materials Science',
    phdType: 'Doctoral Program',
    deadline: 'January (April) / July (October)',
    aprilDeadline: 'January',
    octoberDeadline: 'July',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'Neutrino physics group',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Strong neutrino physics. Affordable city.',
  },
  {
    id: 'niigata-u',
    name: 'Niigata University',
    city: 'Niigata',
    prefecture: 'Niigata',
    type: 'National University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.niigata-u.ac.jp/en/',
    fields: 'Condensed Matter|Nuclear Physics|Astrophysics',
    phdType: 'Doctoral Program',
    deadline: 'December (April) / June (October)',
    aprilDeadline: 'December',
    octoberDeadline: 'June',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'Nuclear physics researchers',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Good nuclear physics. Snowy winters. Affordable.',
  },
  {
    id: 'kanazawa-u',
    name: 'Kanazawa University',
    city: 'Kanazawa',
    prefecture: 'Ishikawa',
    type: 'National University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.kanazawa-u.ac.jp/e/',
    fields: 'Condensed Matter|Quantum Mechanics|Materials Science|Nanotechnology',
    phdType: 'Doctoral Program',
    deadline: 'January (April) / July (October)',
    aprilDeadline: 'January',
    octoberDeadline: 'July',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'Nano materials groups',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Beautiful historic city. Strong in nanotechnology and materials.',
  },
  {
    id: 'chiba-u',
    name: 'Chiba University',
    city: 'Chiba',
    prefecture: 'Chiba',
    type: 'National University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.chiba-u.ac.jp/e/',
    fields: 'Condensed Matter|Biophysics|Materials Science|Quantum Mechanics',
    phdType: 'Doctoral Program',
    deadline: 'January (April) / July (October)',
    aprilDeadline: 'January',
    octoberDeadline: 'July',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'Molecular motors group (Biophysics)',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Near Tokyo. Good biophysics programs.',
  },
  {
    id: 'shizuoka-u',
    name: 'Shizuoka University',
    city: 'Shizuoka',
    prefecture: 'Shizuoka',
    type: 'National University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.shizuoka.ac.jp/en/',
    fields: 'Condensed Matter|Materials Science|Optics',
    phdType: 'Doctoral Program',
    deadline: 'January (April) / July (October)',
    aprilDeadline: 'January',
    octoberDeadline: 'July',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'Optics and materials groups',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Near Mt. Fuji. Good optics research.',
  },
  {
    id: 'yokohama-nu',
    name: 'Yokohama National University',
    city: 'Yokohama',
    prefecture: 'Kanagawa',
    type: 'National University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.ynu.ac.jp/english/',
    fields: 'Condensed Matter|Materials Science|Quantum Mechanics',
    phdType: 'Doctoral Program',
    deadline: 'January (April) / July (October)',
    aprilDeadline: 'January',
    octoberDeadline: 'July',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'Materials science faculty',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Near Tokyo. Good materials science.',
  },
  {
    id: 'kavli-ipmu',
    name: 'Kavli IPMU (University of Tokyo)',
    city: 'Kashiwa',
    prefecture: 'Chiba',
    type: 'Research Institute',
    department: 'Kavli Institute for the Physics and Mathematics of the Universe',
    researchGroup: null,
    url: 'https://www.ipmu.jp/',
    fields: 'Astrophysics|Particle Physics|Cosmology|Mathematical Physics|Neutrino Physics',
    phdType: 'Joint PhD with UTokyo',
    deadline: 'Via UTokyo schedule',
    aprilDeadline: 'December',
    octoberDeadline: 'April',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | Kavli Fellowship',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'Masahiro Kawasaki (Cosmology)|Hitoshi Murayama (Particle Physics)',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'World-leading astrophysics and cosmology institute. Apply through UTokyo. English is the working language.',
  },
  {
    id: 'ehime-u',
    name: 'Ehime University',
    city: 'Matsuyama',
    prefecture: 'Ehime',
    type: 'National University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.ehime-u.ac.jp/english/',
    fields: 'Particle Physics|Neutrino Physics|Condensed Matter',
    phdType: 'Doctoral Program',
    deadline: 'January (April) / July (October)',
    aprilDeadline: 'January',
    octoberDeadline: 'July',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'Neutrino physics (Super-Kamiokande affiliated)',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Strong neutrino physics. Beautiful island setting. Lower cost of living.',
  },
  {
    id: 'miyazaki-u',
    name: 'University of Miyazaki',
    city: 'Miyazaki',
    prefecture: 'Miyazaki',
    type: 'National University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.miyazaki-u.ac.jp/en/',
    fields: 'Condensed Matter|Materials Science',
    phdType: 'Doctoral Program',
    deadline: 'January (April) / July (October)',
    aprilDeadline: 'January',
    octoberDeadline: 'July',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: false,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: true,
    englishTest: 'JLPT N2 preferred',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University',
    requiredDocuments: 'Research proposal|Transcripts|JLPT or English test|References',
    notableProfessors: 'Materials science researchers',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Warm climate. Smaller program. Japanese language may be needed.',
  },
  {
    id: 'ritsumei-u',
    name: 'Ritsumeikan University',
    city: 'Kyoto',
    prefecture: 'Kyoto',
    type: 'Private University',
    department: 'Department of Physics, College of Science and Engineering',
    researchGroup: null,
    url: 'https://en.ritsumei.ac.jp/',
    fields: 'Particle Physics|Condensed Matter|Quantum Mechanics|Materials Science',
    phdType: 'Doctoral Program',
    deadline: 'November (April) / May (October)',
    aprilDeadline: 'November',
    octoberDeadline: 'May',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 800000,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University Scholarship',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'Belle II collaboration members',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Private but MEXT eligible. Involved in Belle II experiment at KEK.',
  },
  {
    id: 'sokendai',
    name: 'SOKENDAI (The Graduate University for Advanced Studies)',
    city: 'Hayama',
    prefecture: 'Kanagawa',
    type: 'Research Institute',
    department: 'Multiple departments via national institutes',
    researchGroup: null,
    url: 'https://www.soken.ac.jp/en/',
    fields: 'Particle Physics|Nuclear Physics|Astrophysics|Condensed Matter|Materials Science|Accelerator Physics',
    phdType: 'Doctoral Program (via KEK/NAOJ/NIFS/IMS)',
    deadline: 'December (April) / June (October)',
    aprilDeadline: 'December',
    octoberDeadline: 'June',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 0,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'All faculty from KEK/NAOJ/NIFS/IMS',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'The only graduate-only university in Japan. Research done at KEK, NAOJ, NIFS, IMS. Full MEXT support. Excellent option!',
  },
  {
    id: 'osaka-city-u',
    name: 'Osaka Metropolitan University',
    city: 'Osaka',
    prefecture: 'Osaka',
    type: 'Public University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.omu.ac.jp/en/',
    fields: 'Condensed Matter|Astrophysics|Materials Science',
    phdType: 'Doctoral Program',
    deadline: 'January (April) / July (October)',
    aprilDeadline: 'January',
    octoberDeadline: 'July',
    aprilIntake: true,
    octoberIntake: true,
    englishProgram: true,
    tuitionJpy: 535800,
    mextDesignated: true,
    jlptRequired: false,
    englishTest: 'TOEFL/IELTS',
    monthlyStipendJpy: 144000,
    fundingType: 'MEXT | University',
    requiredDocuments: 'Research proposal|Transcripts|English test|References',
    notableProfessors: 'Astrophysics researchers',
    rikenAffiliated: false,
    watchlisted: false,
    lastUpdated: '2025-01',
    notesForNepali: 'Recently merged university. Good astrophysics.',
  },
]

// ─────────────────────────────────────────────
// MEXT & SCHOLARSHIP INFO
// ─────────────────────────────────────────────
export const scholarships: ScholarshipInfo[] = [
  {
    id: 'mext-research',
    title: 'MEXT Research Scholarship',
    category: 'MEXT',
    content: 'Japanese Government (MEXT) Scholarship for Research Students. Full funding: ¥144,000/month, tuition waiver, round-trip airfare. Apply through Japanese Embassy in Kathmandu. Deadline: Usually April each year for following April intake. Most popular route for Nepali students.',
  },
  {
    id: 'mext-university-rec',
    title: 'MEXT University Recommendation',
    category: 'MEXT',
    content: 'MEXT Scholarship via University Recommendation. Same benefits as embassy route but you apply directly to the university. University nominates you to MEXT. Deadline: Varies by university (usually November-January). Good option if you have supervisor contact.',
  },
  {
    id: 'jsps-dc1',
    title: 'JSPS DC1 Fellowship',
    category: 'JSPS',
    content: 'Japan Society for the Promotion of Science DC1 Fellowship for first-year PhD students. ¥200,000/month for 3 years. Research allowance ¥1,180,000/year. Apply after enrollment. Very competitive but excellent funding.',
  },
  {
    id: 'jsps-dc2',
    title: 'JSPS DC2 Fellowship',
    category: 'JSPS',
    content: 'JSPS DC2 Fellowship for second-year+ PhD students. ¥200,000/month for 2 years. Similar to DC1 but for those already enrolled. Research allowance included.',
  },
  {
    id: 'jsps-postdoc',
    title: 'JSPS Postdoctoral Fellowship',
    category: 'JSPS',
    content: 'JSPS Postdoctoral Fellowship for foreign researchers. ¥362,000/month for 1-2 years. For after PhD completion. Research allowance ¥1,580,000/year.',
  },
  {
    id: 'riken-jra',
    title: 'RIKEN Junior Research Associate (JRA)',
    category: 'RIKEN',
    content: 'RIKEN JRA Program for doctoral students. ¥200,000+/month stipend. Conduct research at RIKEN while enrolled at a university. Joint PhD arrangement. English is working language. Apply twice yearly (April & October intake).',
  },
  {
    id: 'monbukagakusho-honors',
    title: 'Monbukagakusho Honors Scholarship',
    category: 'MEXT',
    content: 'Additional ¥48,000/month for privately financed international students with excellent academic records. Can be combined with other funding. Apply through your university after enrollment.',
  },
  {
    id: 'jasso-scholarship',
    title: 'JASSO Scholarship',
    category: 'Government',
    content: 'Japan Student Services Organization scholarship for international students. ¥48,000/month. For self-funded students. Apply through university. Less competitive than MEXT.',
  },
  {
    id: 'kosei-fellowship',
    title: 'Rotary Yoneyama Memorial Fellowship',
    category: 'Foundation',
    content: 'Rotary Yoneyama Memorial Scholarship for international students. ¥100,000-140,000/month. Must be recommended by Rotary Club. Apply through university or Rotary Club in Japan.',
  },
  {
    id: 'mext-teacher-training',
    title: 'MEXT Teacher Training Scholarship',
    category: 'MEXT',
    content: 'For teachers and academic staff. 18 months in Japan. ¥143,000/month. Not for regular PhD but useful for university lecturers from Nepal.',
  },
  {
    id: 'world-intl',
    title: 'World International Scholarship (Various)',
    category: 'Foundation',
    content: 'Various private foundations offer scholarships: Ito Foundation, Matsumae International Foundation, Heiwa Nakajima Foundation. ¥120,000-200,000/month. Check JASSO scholarship database for current listings.',
  },
  {
    id: 'embassy-nepal',
    title: 'Embassy of Japan in Nepal - MEXT Application',
    category: 'MEXT',
    content: 'Embassy of Japan in Nepal: Panipokhari, Kathmandu. MEXT Research Scholarship application usually opens in April each year. Written exam in July. Interview in August. Contact: +977-1-4426680. Website: https://www.np.emb-japan.go.jp/',
  },
]

// ─────────────────────────────────────────────
// HELPER: Search scholarships
// ─────────────────────────────────────────────
export function searchScholarships(query: string): ScholarshipInfo[] {
  const q = query.toLowerCase()
  return scholarships.filter(s =>
    s.title.toLowerCase().includes(q) ||
    s.category.toLowerCase().includes(q) ||
    s.content.toLowerCase().includes(q)
  )
}
